### ISSUE TITLE
Order of the patch

### ISSUE THREAD

**Issue by Saaldiener** [praecipitator/PatchSplitterTest#1]
I'm new. I love it when people preface their comments with this to avoid nasty rebuttals. If I put the patch at the top of the order of patches it runs with the others at the same time. Sounds great so far, but only one patch is written to the output. If I put it at the bottom of the patch order, then it takes a long time to process. I finally x'd out of it at 22mins. I'm confused.  Maybe it's because I'm listening to Pink Floyd's latest album.

**Comment by praecipitator** [comment]
I'm not sure what you are trying to say, but this is NOT a patcher which is intended for any actual use. It's just some test code I was fooling around with.
